//! Passphrase-encrypted portable secret snapshots.
//!
//! The ciphertext is safe to track in Git. Decrypted values are written only to
//! a mode-0600 local environment file that Synapse-managed shells source.

use std::collections::BTreeMap;
use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use age::secrecy::{ExposeSecret, SecretString};

pub const STACK_SECRETS_FILE: &str = "secrets.age";
const SECRET_FORMAT_VERSION: u8 = 1;
const LOCAL_SECRETS_FILE: &str = "secrets.env";
static TEMP_COUNTER: AtomicU64 = AtomicU64::new(0);

#[derive(serde::Serialize, serde::Deserialize)]
struct SecretSnapshot {
    version: u8,
    values: BTreeMap<String, String>,
}

pub fn prompt_new_passphrase() -> io::Result<SecretString> {
    let passphrase =
        SecretString::from(rpassword::prompt_password("Secret snapshot passphrase: ")?);
    if passphrase.expose_secret().is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "secret snapshot passphrase cannot be empty",
        ));
    }

    let confirmation = SecretString::from(rpassword::prompt_password("Confirm passphrase: ")?);
    if passphrase.expose_secret() != confirmation.expose_secret() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "secret snapshot passphrases do not match",
        ));
    }

    Ok(passphrase)
}

pub fn prompt_passphrase() -> io::Result<SecretString> {
    let passphrase =
        SecretString::from(rpassword::prompt_password("Secret snapshot passphrase: ")?);
    if passphrase.expose_secret().is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "secret snapshot passphrase cannot be empty",
        ));
    }
    Ok(passphrase)
}

pub fn write_snapshot(
    path: &Path,
    values: &BTreeMap<String, String>,
    passphrase: &SecretString,
) -> io::Result<()> {
    validate_values(values)?;
    let snapshot = SecretSnapshot {
        version: SECRET_FORMAT_VERSION,
        values: values.clone(),
    };
    let plaintext = serde_json::to_vec(&snapshot)
        .map_err(|error| io::Error::other(format!("cannot encode secret snapshot: {error}")))?;
    let recipient = age::scrypt::Recipient::new(passphrase.clone());
    let ciphertext = age::encrypt(&recipient, &plaintext)
        .map_err(|error| io::Error::other(format!("cannot encrypt secret snapshot: {error}")))?;
    write_private(path, &ciphertext)
}

pub fn read_snapshot(
    path: &Path,
    passphrase: SecretString,
) -> io::Result<BTreeMap<String, String>> {
    let ciphertext = fs::read(path)?;
    let identity = age::scrypt::Identity::new(passphrase);
    let plaintext = age::decrypt(&identity, &ciphertext).map_err(|_| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            "wrong secret snapshot passphrase or corrupted snapshot",
        )
    })?;
    let snapshot: SecretSnapshot = serde_json::from_slice(&plaintext).map_err(|_| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            "secret snapshot has an unsupported format",
        )
    })?;
    if snapshot.version != SECRET_FORMAT_VERSION {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("unsupported secret snapshot version {}", snapshot.version),
        ));
    }
    validate_values(&snapshot.values)?;
    Ok(snapshot.values)
}

pub fn write_local_environment(values: &BTreeMap<String, String>) -> io::Result<PathBuf> {
    validate_values(values)?;
    let mut content = String::from("# Generated by Synapse. Contains secrets; mode 0600.\n");
    for (name, value) in values {
        content.push_str("export ");
        content.push_str(name);
        content.push('=');
        content.push_str(&shell_quote(value));
        content.push('\n');
    }

    let path = crate::state::config_dir().join(LOCAL_SECRETS_FILE);
    write_private(&path, content.as_bytes())?;
    Ok(path)
}

pub fn valid_env_name(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some('A'..='Z' | 'a'..='z' | '_'))
        && chars.all(|character| character.is_ascii_alphanumeric() || character == '_')
}

fn validate_values(values: &BTreeMap<String, String>) -> io::Result<()> {
    for (name, value) in values {
        if !valid_env_name(name) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                format!("secret snapshot contains invalid environment name {name:?}"),
            ));
        }
        if value.contains('\0') {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                format!("secret snapshot value {name:?} contains a NUL byte"),
            ));
        }
    }
    Ok(())
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn write_private(path: &Path, contents: &[u8]) -> io::Result<()> {
    let parent = path.parent().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("{} has no parent directory", path.display()),
        )
    })?;
    fs::create_dir_all(parent)?;

    let temporary = parent.join(format!(
        ".{}.synapse-{}-{}",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("secret"),
        std::process::id(),
        TEMP_COUNTER.fetch_add(1, Ordering::Relaxed),
    ));
    let result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&temporary)?;
        file.write_all(contents)?;
        file.sync_all()?;
        drop(file);
        fs::set_permissions(&temporary, fs::Permissions::from_mode(0o600))?;
        fs::rename(&temporary, path)?;
        Ok(())
    })();
    if result.is_err() {
        fs::remove_file(&temporary).ok();
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn encrypted_snapshot_round_trip() {
        let dir = tempdir().unwrap();
        let path = dir.path().join(STACK_SECRETS_FILE);
        let values = BTreeMap::from([
            (
                "API_TOKEN".to_string(),
                "correct horse battery staple".to_string(),
            ),
            ("WITH_QUOTE".to_string(), "don't leak me".to_string()),
        ]);
        let passphrase = SecretString::from("test passphrase".to_string());

        write_snapshot(&path, &values, &passphrase).unwrap();

        let ciphertext = fs::read(&path).unwrap();
        assert!(!ciphertext
            .windows(b"correct horse battery staple".len())
            .any(|window| window == b"correct horse battery staple"));
        assert_eq!(read_snapshot(&path, passphrase).unwrap(), values);
    }

    #[test]
    fn wrong_passphrase_cannot_decrypt_snapshot() {
        let dir = tempdir().unwrap();
        let path = dir.path().join(STACK_SECRETS_FILE);
        let values = BTreeMap::from([("API_TOKEN".to_string(), "secret".to_string())]);

        write_snapshot(&path, &values, &SecretString::from("correct".to_string())).unwrap();
        let error = read_snapshot(&path, SecretString::from("wrong".to_string())).unwrap_err();

        assert_eq!(error.kind(), io::ErrorKind::InvalidData);
    }

    #[test]
    fn local_environment_is_shell_quoted_and_private() {
        let quoted = shell_quote("a'$(not executed)\nvalue");
        assert_eq!(quoted, "'a'\\''$(not executed)\nvalue'");

        let dir = tempdir().unwrap();
        let path = dir.path().join("secrets.env");
        write_private(&path, b"export TOKEN='value'\n").unwrap();

        assert_eq!(
            fs::metadata(path).unwrap().permissions().mode() & 0o777,
            0o600
        );
    }
}
